version: "3.8"
services:
  client:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
#    depends_on:
#      - server

  server:
    build: ./server
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
    command: yarn run dev

  postgres-db:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local